server:
  port: 8802

spring:
  application:
    name: mall-order
  datasource:
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/mall_order?characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  cloud:
    nacos:
      server-addr: localhost:8848  #nacos服务地址

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    banner: false
  mapper-locations: classpath*:/mapper/**/*.xml

seata: # 配置seata
  tx-service-group: mygroup
  service:
    vgroup-mapping:
      mygroup: default
  client:
    undo:
      log-serialization: kryo # 改变undo_log的序列化方式